backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "status" # Used in routes, e.g., /admin/collections/blog
    label: "status" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter. 
    # Remove any that aren't needed for posts
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Type", name: "type", widget: "hidden", default: "status"}
      - {label: "Status", name: "title", widget: "string"}
  - name: "clanok" # Used in routes, e.g., /admin/collections/blog
    label: "článok" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter. 
    # Remove any that aren't needed for posts
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Type", name: "type", widget: "hidden", default: "clanok"}
      - {label: "Titulok", name: "title", widget: "string"}
      - {label: "Obrázok", name: "thumbnail", widget: "image"}  
      - {label: "Link", name: "url", widget: "string"}
      - {label: "Výcuc", name: "vycuc", widget: "string"}     
